### PR TITLE
Feature/kotlin features

### PR DESCRIPTION
**Pull request by mario222k**
I add divider and fixed the item layout height issue.

Additionally i changed some kotlin parts to a way you hopefully like.

Feel free to contact me ✉️

--- EDIT:

i see you fixed it already... looks good :) then please ignore this or feel free to read it for the kotlin part

### CODE REVIEW

**Comment by isnirp** [comment]
thanks for the feedback Mario

**Comment by isnirp** [comment]
Hi Mario, after the interview was told I had the position after the interview. but unfortunately I had a mail that said otherwise yesterday. I would like to know if anything was the problem

**Comment by mario222k** [comment]
I hope this email will reach you.

Unfortunately i don't know either. We had the GO for two Android Seniors
and now the Comany announced that it will be only one. And we had you and
somebody else who showed a slightly more skills.

Anyway you have no reason to be ashamed. We found your work and person well
fitting for our team. I personally found it really great that you used
Kotlin and Picasso. ;D

I am truthfully sorry that it ended liked this.

----------

One addition to my pull request... Your kotlin class within other classes
are completely fine. I forgot that inner classes have to be announced
seperately.

Am 01.06.2017 16:44 schrieb "Prince Amankwah" <notifications@github.com>:

**Comment by isnirp** [comment]
Thank you Mario  for taking the time to explain things to me. I also appreciate the opportunity that I was given.

**Pull request closed without merging**
